name: Setup
description: Set up and cache PHP, Composer, and Node for Coffer.

inputs:
  php-version:
    description: PHP version to use.
    required: false
    default: '8.5'
  php-extensions:
    description: PHP extensions to install.
    required: false
    default: dom, curl, libxml, mbstring, zip, pcntl, sqlite3, pdo_sqlite

runs:
  using: composite
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        ini-values: error_reporting=E_ALL
        tools: composer:v2
        coverage: none

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Cache Composer Dependencies
      uses: actions/cache@v5
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: npm
