blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/refringe/coffer/discussions
    about: For questions, help, or general discussion, please start a discussion instead of opening an issue.
